name: "Pa11y CI Accessibility Audit"
description: "Run pa11y-ci accessibility checks on one or more URLs and generate a JSON report."
author: "Idil Saglam"

inputs:
  urls:
    description: "One or more URLs to test, separated by newlines."
    required: true
  output:
    description: "Path where the JSON report will be written."
    required: false
    default: "pa11y-report.json"

outputs:
  report-path:
    description: "Path of the generated JSON report."

runs:
  using: "node20"
  main: "src/index.js"
